/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventFormFormRouteImport } from './routes/event/form/form'
import { Route as EventFormEventIdRouteImport } from './routes/event/form/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventFormFormRoute = EventFormFormRouteImport.update({
  id: '/event/form/form',
  path: '/event/form/form',
  getParentRoute: () => rootRouteImport,
} as any)
const EventFormEventIdRoute = EventFormEventIdRouteImport.update({
  id: '/event/form/$eventId',
  path: '/event/form/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event/form/$eventId': typeof EventFormEventIdRoute
  '/event/form/form': typeof EventFormFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/form/$eventId': typeof EventFormEventIdRoute
  '/event/form/form': typeof EventFormFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event/form/$eventId': typeof EventFormEventIdRoute
  '/event/form/form': typeof EventFormFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/event/form/$eventId' | '/event/form/form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/event/form/$eventId' | '/event/form/form'
  id: '__root__' | '/' | '/event/form/$eventId' | '/event/form/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventFormEventIdRoute: typeof EventFormEventIdRoute
  EventFormFormRoute: typeof EventFormFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/form/form': {
      id: '/event/form/form'
      path: '/event/form/form'
      fullPath: '/event/form/form'
      preLoaderRoute: typeof EventFormFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/form/$eventId': {
      id: '/event/form/$eventId'
      path: '/event/form/$eventId'
      fullPath: '/event/form/$eventId'
      preLoaderRoute: typeof EventFormEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventFormEventIdRoute: EventFormEventIdRoute,
  EventFormFormRoute: EventFormFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
